DROP TABLE IF EXISTS TASK;

CREATE TABLE TASK
(
    TASK        VARCHAR(250) PRIMARY KEY,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    TEST_INPUT   VARCHAR(250)  NOT NULL,
    TEST_OUTPUT  VARCHAR(250)  NOT NULL
);
